sudo: required
language: python
python:
  - "3.6"

script:
  - sudo apt-get install pandoc
  - pandoc -v
  - pandoc --self-contained --to=html -o README.html README.md
  - ls
#  - sudo apt-get install texlive-xetex
#  - sudo apt-get install texlive-latex-recommended
#  - pip install -I dropbox
#  - pip install jupyter
#  - sudo apt-get install python-software-properties
#  - sudo add-apt-repository -y ppa:libreoffice/ppa
#  - sudo apt-get update -y
#  - sudo apt-get install -y libreoffice-writer libreoffice-impress libreoffice-calc
#  - python .continuous_integration/convert_and_send.py

cache:
  pip: true
  apt: true
  directories:
    - .cached_sha1_checksum

notifications:
  email: false
