sudo: required
language: python
python:
  - "3.5"

script:
  - sudo apt-get install texlive-xetex
  - sudo apt-get install texlive-latex-recommended
  - pip install -I dropbox==6.9.0
  - pip install jupyter
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update -y
  - sudo apt-get install -y libreoffice-writer libreoffice-impress libreoffice-calc
  - sudo apt-get install pandoc
  - python .continuous_integration/convert_and_send.py

cache:
  pip: true
  apt: true
  directories:
    - .cached_sha1_checksum

notifications:
  email: false
