sudo: required
language: python
python:
  - "3.6"

script:
  - sudo wget --quiet https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb -O _pandoc.deb
  - sudo dpkg -i _pandoc.deb
  - sudo apt-get install texlive-xetex
  - sudo apt-get install texlive-latex-recommended
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install texlive-latex-extra
  - pandoc --latex-engine=xelatex "README (copy).md" -o "README (copy).pdf"
#  - pip install -I dropbox
#  - pip install jupyter
#  - sudo apt-get install python-software-properties
#  - sudo add-apt-repository -y ppa:libreoffice/ppa
#  - sudo apt-get update -y
#  - sudo apt-get install -y libreoffice-writer libreoffice-impress libreoffice-calc
#  - python .continuous_integration/convert_and_send.py

cache:
  wget: true
  pip: true
  apt: true
  directories:
    - .cached_sha1_checksum

notifications:
  email: false
