#sudo: required
language: python
python:
  - "3.6"

script:
  - sudo wget --quiet https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb -O _pandoc.deb
  - sudo dpkg -i _pandoc.deb
  - sudo apt-get update -y
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra python-software-properties
#  - cd markdown_files
#  - pandoc --latex-engine=xelatex -o "Microbial work.pdf" "Microbial work.md"
#  - python -c "import subprocess;cmd=['pandoc', '--latex-engine=xelatex', '-o', 'Microbial work.pdf', 'Microbial work.md'];result = subprocess.run( cmd, stdout=subprocess.PIPE)"
#  - ls
#  - pandoc --latex-engine=xelatex "README.md" -o "README.pdf"
#  - pandoc --self-contained --to=html -o README.html README.md
  - pip install -I dropbox
  - pip install jupyter
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update -y
  - sudo apt-get install -y libreoffice-writer libreoffice-impress libreoffice-calc
  - python .continuous_integration/convert_and_send.py

cache:
  wget: true
  pip: true
  apt: true
  directories:
    - .cached_sha1_checksum

notifications:
  email: false
